### PR TITLE
feat: Add write next version support for make projects

### LINKED ISSUE #112: Write next version in a make file
### Feature Request
Updating the make file  with the next calculated version.

### PR DESCRIPTION
**Pull request by anoopmsivadas**
* Fixes #112 
* Added writeNextVersion method for Make Project
* Added Testcases for the Make project

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by ADI10HERO** [comment]
Hey @anoopmsivadas , can you please fix the checkstyle errors, Thanks!

**Comment by anoopmsivadas** [comment]
> Hey @anoopmsivadas , can you please fix the checkstyle errors, Thanks!

Hi @ADI10HERO, I have reformatted the code, could you please run the work flow again. Thanks!

**Comment by ADI10HERO** [comment]
Hey @anoopmsivadas, good job in bringing down checkstyles bugs from 123 to 14.

Please note that we are using google style checks and I'd also suggest that you run the same locally (or configure your ide to do that for you), the command is: 
`mvn --no-transfer-progress checkstyle:check`

**Comment by anoopmsivadas** [comment]
> Hey @anoopmsivadas, good job in bringing down checkstyles bugs from 123 to 14.
> 
> Please note that we are using google style checks and I'd also suggest that you run the same locally (or configure your ide to do that for you), the command is: `mvn --no-transfer-progress checkstyle:check`

Hey @ADI10HERO, thanks for letting me know, should have asked that earlier 😬 . Now it should be fine, have tested locally. Please review at your convenience.

**Review by philippart-s — APPROVED** [review]
for me it's ok.
@ADI10HERO I let you finish the review, for your information I did test in a Jenkins instance and it do the job :wink:

**Comment by ADI10HERO** [comment]
> for me it's ok. @ADI10HERO I let you finish the review, for your information I did test in a Jenkins instance and it do the job 😉

Thanks for doing that @philippart-s, that's what I was gonna do... I was facing some problems running the make command and that's why the review was taking time 😅

**Pull request merged**
