### PR TITLE
fix: correct checkstyle errors

### LINKED ISSUE #71: fix existing checkstyle issues
### Reproduction steps

- `mvn check`

### Results

Expected result:

NO checkstyle violations

Actual result:
94 checkstyle violations

### PR DESCRIPTION
**Pull request by ADI10HERO**
fixes #71 

This PR fixes the existing checkstyle errors.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by kwhetstone** [comment]
Oh this is great!

**Comment by philippart-s** [comment]
good stuff (comments realy help for new contributors :wink: .
I saw that th code I wrote is refactored with two spaces instead of 4, is that correct ?
It's to help me to choose the first configuration for the #51

**Comment by ADI10HERO** [comment]
Hello @philippart-s,
Good observation... 
Is it correct? I am not sure, I think, It will depend on what we decide.

Steps that I took:
1. Used the `mvn check` command to see errors.
2. I saw some whitespace related errors & some wrong indentation errors
3. Instead of manually changing those, I installed checkstyle plugin for IntelliJ Idea IDE
4. Set the style to google styles and clicked "Reformat Code", it changed the following:
       - Import order (which I had to undo manually)
       - Indentation (4 --> 2)
       - Trim whitespace and remove extra newlines  
5. Manually fixed other errors :)

**Comment by philippart-s** [comment]
As I proposed in the https://github.com/jenkinsci/conventional-commits-plugin/issues/51#issuecomment-881937418 we can add the checkstyle verification in the maven's lifecycle project to check that the project is well formatting (and respect other good coding rules :wink: ).
At this point if we do this we will choose what configuration of checkstyle apply (goole, sun, custom).

To me the main advantage is to make easier the peer reviewing in the GitHub PR.

Otherwise if you and other maintainers think it's not necessary you can close the issue number #51 .

**Review by garethjevans — APPROVED** [review]

**Pull request merged**
