### PR TITLE
docs: Add CONTRIBUTING.md

### LINKED ISSUE #70: Add contributing.md
### Feature Request

A go-to file for the users to contribute/add more project types to the project

### PR DESCRIPTION
**Pull request by abxhr**
This PR adds `CONTRIBUTING.md` to the repository.

Fixes #70 

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by philippart-s** [comment]
@abxhr   It's a good job ! 

I think you can add two points : 
 - add a link in the footer of the README
 - link to the generic CONTIBUTING file (the actual one in the README)

**Comment by abxhr** [comment]
@philippart-s I have made the requested additions ✅

**Review by philippart-s — APPROVED** [review]
:rocket: Goos job !

**Comment by philippart-s** [comment]
@garethjevans  & @ADI10HERO ok for you ?

**Pull request merged**
